# Generated by Django 2.2 on 2020-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0002_people")]

    operations = [
        migrations.AddField(
            model_name="people", name="number", field=models.IntegerField(default=66)
        )
    ]
