# Generated by Django 2.2 on 2020-03-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("posts", "0007_auto_20200315_0509")]

    operations = []
