# Generated by Django 2.2 on 2020-03-18 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0007_auto_20200315_0509")]

    operations = [
        migrations.AlterField(
            model_name="comment", name="text", field=models.TextField(max_length=5000)
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_by_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts_in_group",
                to="posts.Group",
            ),
        ),
    ]
