# Generated by Django 2.2 on 2020-03-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_delete_people"),
        ("posts", "0009_auto_20200318_2042"),
    ]

    operations = []
