# Generated by Django 2.2 on 2020-03-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("posts", "0010_merge_20200318_2045")]

    operations = [migrations.DeleteModel(name="People")]
