version: '3.8'
volumes:
    postgres_data:
    static:
services:
    db:
        image: postgres:12.0
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.docker
    web:
        build: ./
        image: thepost:latest
        depends_on:
            - db
        volumes:
            - static:/app/static
        expose:
            - 8000
        env_file:
            - ./.env.docker
    nginx:
        build: ./nginx
        image: nginx:1.19.2
        depends_on:
            - web
        volumes:
            - static:/app/static
        ports:
            - ${PORT}:80
