branch-defaults:
  master:
    environment: thepost
    group_suffix: null
environment-defaults:
  thepost:
    branch: master
    repository: origin
global:
  application_name: thepost
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
